name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Create .env file from secret
        run: |
          echo "$ENV_FILE" > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Verify .env file creation
        run: cat .env

      - name: Build
        run: go build -v ./...

      - name: Docker image build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN_KEY }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_HUB_USERNAME }}/candle-collector:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/candle-collector:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }} # pem 키
          # 도커 작업
          script: |
            docker stop collector
            docker rm collector
            docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/candle-collector:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/candle-collector:latest
            docker run -d -p 8081:8081 --name collector ${{ secrets.DOCKER_HUB_USERNAME }}/candle-collector:latest