name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Create .env file from secret
        run: |
          echo "$ENV_FILE" > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Verify .env file creation
        run: cat .env

      - name: Build
        run: go build -v ./...

      - name: Docker image build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN_KEY }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_HUB_USERNAME }}/candle-collector:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/candle-collector:latest